//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S1.L01C.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S1.L01C.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Växelpengar - Nivå C  (Johnny Pesola 2014).
        /// </summary>
        internal static string applicationTitle {
            get {
                return ResourceManager.GetString("applicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-kronor.
        /// </summary>
        internal static string denomination1 {
            get {
                return ResourceManager.GetString("denomination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-kronor.
        /// </summary>
        internal static string denomination10 {
            get {
                return ResourceManager.GetString("denomination10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100-lappar.
        /// </summary>
        internal static string denomination100 {
            get {
                return ResourceManager.GetString("denomination100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20-lappar.
        /// </summary>
        internal static string denomination20 {
            get {
                return ResourceManager.GetString("denomination20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-kronor.
        /// </summary>
        internal static string denomination5 {
            get {
                return ResourceManager.GetString("denomination5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50-lappar.
        /// </summary>
        internal static string denomination50 {
            get {
                return ResourceManager.GetString("denomination50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500-lappar.
        /// </summary>
        internal static string denomination500 {
            get {
                return ResourceManager.GetString("denomination500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck på en tangent för ny beräkning - Esc avslutar..
        /// </summary>
        internal static string escapeOrResumeMsg {
            get {
                return ResourceManager.GetString("escapeOrResumeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontant.
        /// </summary>
        internal static string receiptCash {
            get {
                return ResourceManager.GetString("receiptCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka.
        /// </summary>
        internal static string receiptChange {
            get {
                return ResourceManager.GetString("receiptChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr.
        /// </summary>
        internal static string receiptCurrency {
            get {
                return ResourceManager.GetString("receiptCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVITTO.
        /// </summary>
        internal static string receiptHeader {
            get {
                return ResourceManager.GetString("receiptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pengar tillbaka.
        /// </summary>
        internal static string receiptMoneyBack {
            get {
                return ResourceManager.GetString("receiptMoneyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        internal static string receiptPieces {
            get {
                return ResourceManager.GetString("receiptPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öresavrundning.
        /// </summary>
        internal static string receiptRoundingOffAmount {
            get {
                return ResourceManager.GetString("receiptRoundingOffAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalt.
        /// </summary>
        internal static string receiptSubtotal {
            get {
                return ResourceManager.GetString("receiptSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Att betala.
        /// </summary>
        internal static string receiptTotal {
            get {
                return ResourceManager.GetString("receiptTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kunde inte tolkas som en giltig summa pengar..
        /// </summary>
        internal static string userInputCouldNotParseMsg {
            get {
                return ResourceManager.GetString("userInputCouldNotParseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL: .
        /// </summary>
        internal static string userInputErrorMsg {
            get {
                return ResourceManager.GetString("userInputErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to är ett för litet belopp.
        /// </summary>
        internal static string userInputValueTooSmallMsg {
            get {
                return ResourceManager.GetString("userInputValueTooSmallMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange totalsumma.
        /// </summary>
        internal static string userReadPositiveDoubleMsg {
            get {
                return ResourceManager.GetString("userReadPositiveDoubleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange erhållet belopp.
        /// </summary>
        internal static string userReadUintMsg {
            get {
                return ResourceManager.GetString("userReadUintMsg", resourceCulture);
            }
        }
    }
}
